update article.md
javascript-tutorial/ml.javascript.info pull request #67
Opened 2021-08-01 13:50 UTC by donamath

Translated the English tutorial to Malayalam

2021-08-01 13:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ml.javascript.info?pullRequest=67) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ml.javascript.info?pullRequest=67) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ml.javascript.info?pullRequest=67) it.</sub>

2021-08-01 15:44 UTC, siddiqkaithodu requested changes
Please dont use online translator when translating the article.
Can you update this with proper translation?
ഇത് അതുപോലെ തന്നെ translate ചെയ്യണമെന്നില്ല.ഇത് വായിക്കുന്നവർക്കു എങ്ങനെ മനസ്സിലാക്കാം എന്ന് നോക്കുക.

Eg: environment നെ പരിസ്ഥിതി എന്നാക്കുന്നതിലും നല്ലത് environment എന്നാകുന്നത് തന്നെയായിരിക്കും.

You can refer translated articles to know their pattern.

2021-08-01 17:55 UTC, MuhammedZakir commented
Either use "user" or "ഉപയോക്താവ്". Don't use them both. Do the same for other words. :-)

2021-08-02 01:39 UTC, siddiqkaithodu commented
Next time raising pull requests, please use the article name as the topic, so the bot will identify what is happening!

2021-08-02 03:01 UTC, siddiqkaithodu commented
Please raise another pull request with the article name as title !

2021-08-02 03:01 UTC, closed without merging

2021-08-02 03:02 UTC, siddiqkaithodu commented
# Interaction: alert, prompt, confirm
ബ്രൗസർ നമ്മൾ ഒരു Demo environment ആയി ഉപയോഗിക്കുന്നതിനാൽ,user-മായി interact ചെയ്യാൻ കുറച്ച് functions നോക്കാം: `alert`, `prompt`, പിന്നെ `confirm`.

## alert

ഇത് നമ്മൾ ഇതിനകം തന്നെ കണ്ടിട്ടുണ്ട്. ഇത് ഒരു alert കാണിക്കുകയും user "OK" അമർത്തുന്നതിനായി കാത്തിരിക്കുകയും ചെയ്യുന്നു.

ഉദാഹരണത്തിന്:

```js run
alert("Hello");
```

alertനോട് കൂടെയുള്ള മിനി-വിൻഡോയെ *modal window* എന്ന് വിളിക്കുന്നു . "modal" എന്ന വാക്കിന്റെ അർത്ഥം, വിൻഡോ കൈകാര്യം ചെയ്യുന്നതുവരെ user ന് പേജിന്റെ ബാക്കി ഭാഗങ്ങളുമായി സംവദിക്കുക, മറ്റ് ബട്ടണുകൾ അമർത്തുക, മുതലായവ പറ്റില്ല. 

Function `prompt` രണ്ട് arguments സ്വീകരിക്കുന്നു:

```js no-beautify
result = prompt(title, [default]);
```

ഇത് ഒരു text message ഉം സന്ദർശകനുള്ള ഇൻപുട്ട് ഫീൽഡും OK/Cancel ബട്ടണുകളും ഉള്ള ഒരു modal window കാണിക്കുന്നു.

`title`
: സന്ദർശകനെ കാണിക്കാനുള്ള text.

`default`
: ഒരു optional 2nd parameter, ഇൻപുട്ട് ഫീൽഡിന്റെ initial value.

```smart header="syntax ഇൽ ഉള്ള square bracket `[...]`"
മുകളിലുള്ള syntax ന്റെ `default` ന് ചുറ്റുമുള്ള square ബ്രാക്കറ്റുകൾ, parameter ഓപ്ഷണൽ ആണെന്ന് സൂചിപ്പിക്കുന്നു,നമുക്ക് വേണമെങ്കിൽ മതി.ഇതിന്റെ ആവശ്യമില്ല.
```

User ന് prompt ഇൻപുട്ട് ഫീൽഡിൽ എന്തെങ്കിലും ടൈപ്പ് ചെയ്ത് OK അമർത്താം. അപ്പോൾ ആ text നമുക്ക്  `result` ൽ ലഭിക്കും. Cancel അമർത്തുന്നതിലൂടെ അവർക്ക് ഇൻപുട്ട് cancel ചെയ്യാനും പറ്റും, `key:Esc` കീ അമർത്തുന്നതിലൂടെ, നമുക്ക് `result`ൽ `null` ലഭിക്കും.

`prompt` ലേക്കുള്ള കോൾ, ഇൻപുട്ട് ഫീൽഡിൽ നിന്ന് text return നൽകുന്നു. ഇൻപുട്ട് cancel ആക്കുകയാണെങ്കിൽ `null` return ചെയ്യും.
ഉദാഹരണത്തിന്:

```js run
let age = prompt('How old are you?', 100);

alert(`You are ${age} years old!`); // You are 100 years old!
```

````warn header="IE ൽ: എപ്പോഴും `default` കൊടുക്കുക"
രണ്ടാമത്തെ parameter ഓപ്ഷണൽ ആണ്, പക്ഷേ നമ്മൾ അത് നൽകുന്നില്ലെങ്കിൽ, ഇന്റർനെറ്റ് എക്സ്പ്ലോറർ `"undefined"` എന്ന് text promptൽ ചേർക്കും.

ഇത് കാണാൻ ഇന്റർനെറ്റ് എക്സ്പ്ലോററിൽ(IE) ഈ കോഡ് പ്രവർത്തിപ്പിക്കുക:
```js run
let test = prompt("Test");
```

അതിനാൽ, IE- ൽ മികച്ചതായി കാണുന്നതിന്, രണ്ടാമത്തെ argument എല്ലായ്പ്പോഴും നൽകാൻ ഞങ്ങൾ നിർദേശിക്കുന്നു:
```js run
let test = prompt("Test", ''); // <--  IE ൽ
```
````

## confirm

syntax:

```js
result = confirm(question);
```

`confirm` function ൽ, ഒരു ചോദ്യവും, OK and Cancel ഉള്ള രണ്ട് ബട്ടണുകളും ഒരു modal വിൻഡോയും ആണ് കാണുന്നത്.
OK അമർത്തിയാൽ ഫലം `true`, അല്ലാത്തപക്ഷം`false`.
ഉദാഹരണത്തിന്:

```js run
let isBoss = confirm("Are you the boss?");

alert( isBoss ); // true if OK is pressed
```

## സംഗ്രഹം

സന്ദർശകരുമായി സംവദിക്കാൻ ഞങ്ങൾ 3 browser-specific പ്രവർത്തനങ്ങൾ ഉൾപ്പെടുത്തി:

`alert`
: ഒരു സന്ദേശം കാണിക്കുന്നു.

`prompt`
: ടെക്സ്റ്റ് ഇൻപുട്ട് ചെയ്യാൻ ഉപയോക്താവിനോട് ആവശ്യപ്പെടുന്ന ഒരു സന്ദേശം കാണിക്കുന്നു. ഇത് text return നൽകുന്നു അല്ലെങ്കിൽ, Cancel ബട്ടൺ, `key: Esc` ക്ലിക്ക് ചെയ്തിട്ടുണ്ടെങ്കിൽ,` null` return ചെയ്യും.

`confirm`
: ഒരു സന്ദേശം കാണിക്കുകയും ഉപയോക്താവ് "OK" അല്ലെങ്കിൽ "Cancel" അമർത്തുന്നതിനായി കാത്തിരിക്കുകയും ചെയ്യുന്നു.ഇത് OK എന്നതിന് `true`, Cancel/`key:Esc` എന്നതിന് `false` എന്നിവ നൽകുന്നു.

ഈ രീതികളെല്ലാം modal ആണ്: അവർ സ്ക്രിപ്റ്റ് execution താൽക്കാലികമായി നിർത്തി, വിൻഡോ dismiss ചെയ്യുന്നതുവരെ സന്ദർശകനെ ബാക്കി പേജുമായി സംവദിക്കാൻ അനുവദിക്കുന്നില്ല.

മുകളിലുള്ള എല്ലാ രീതികളിലും common ആയി രണ്ട് പരിമിതികളുണ്ട്:
1. modal വിൻഡോയുടെ കൃത്യമായ സ്ഥാനം ബ്രൗസർ നിർണ്ണയിക്കുന്നു. സാധാരണയായി, അത് നടുവിലായിട്ടാണ്.
2. വിൻഡോയുടെ കൃത്യമായ രൂപവും ബ്രൗസറിനെ ആശ്രയിച്ചിരിക്കുന്നു. നമ്മൾക്ക് അത് modify ചെയ്യാൻ കഴിയില്ല.

User മായി ഇടപെടലുകൾ കാണിക്കാൻ ഇതിലും നല്ല മറ്റ് വഴികളുണ്ട്, പക്ഷേ നിസാരമായ ഈ പരിമിതികൾ നമ്മൾ കാര്യമാക്കുന്നില്ലെങ്കിൽ, ഈ 3 രീതികൾ നന്നായി തന്നെ നമുക്ക് ധാരാളം.

2021-08-02 03:03 UTC, siddiqkaithodu commented
Try with the above☝️.

2021-08-02 05:41 UTC, donamath commented
> Either use "user" or "ഉപയോക്താവ്". Don't use them both. Do the same for other words. :-)

Which is recommended? "user" or "ഉപയോക്താവ്" ?

2021-08-02 06:44 UTC, MuhammedZakir commented
> > Either use "user" or "ഉപയോക്താവ്". Don't use them both. Do the same for other words. :-)
> 
> Which is recommended? "user" or "ഉപയോക്താവ്" ?

ഉപയോക്താവ്. However, do use "user" for variable names and when referring to them.